[encoder]
channels = [24, 48, 64, 128, 160, 256]
downsampling_factors = [[1, 1, 1], [1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]
stage_depths = [1, 2, 2, 3, 4, 15]
block_factory = [
    "InvertedBottleneck2Plus1",
    "InvertedBottleneck2Plus1",
    "InvertedBottleneck2Plus1",
    "InvertedBottleneck2Plus1",
    "InvertedBottleneck2Plus1",
    "InvertedBottleneck2Plus1",
]
block_factory_args = [
    {expansion_factor=1, normalization_factory="RMSNorm", excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {expansion_factor=4, normalization_factory="RMSNorm", excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {expansion_factor=4, normalization_factory="RMSNorm", excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {expansion_factor=4, normalization_factory="RMSNorm", excitation_ratio=0.25, anti_aliasing=false},
    {expansion_factor=6, normalization_factory="RMSNorm", excitation_ratio=0.25, anti_aliasing=false},
    {expansion_factor=6, normalization_factory="RMSNorm", excitation_ratio=0.25, anti_aliasing=false},
]
aggregation_factory = "Linear3d"

[decoder]
channels = [160, 128, 64, 48, 24]
upsampling_factors = [[1, 2, 2], [1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 1, 1]]
upsampling_factory = "Trilinear"
stage_depths = [4, 3, 2, 2, 1]
block_factory = [
    "InvertedBottleneck2Plus1",
    "InvertedBottleneck2Plus1",
    "InvertedBottleneck2Plus1",
    "InvertedBottleneck2Plus1",
    "InvertedBottleneck2Plus1",
]
block_factory_args = [
    {expansion_factor=6, normalization_factory="RMSNorm", excitation_ratio=0.25, anti_aliasing=false},
    {expansion_factor=4, normalization_factory="RMSNorm", excitation_ratio=0.25, anti_aliasing=false},
    {expansion_factor=4, normalization_factory="RMSNorm", excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {expansion_factor=4, normalization_factory="RMSNorm", excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {expansion_factor=1, normalization_factory="RMSNorm", excitation_ratio=0.0, fused=true, anti_aliasing=false},
]
aggregation_factory = "Linear3d"
skip_connections=true

