[encoder]
channels = [29, 58, 77, 154, 192, 307]
downsampling_factors = [1, 2, 2, 2, 2]
stage_depths = [1, 3, 3, 4, 6, 21]
block_factory = [
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
]
block_factory_args = [
    {expansion_factor=1, excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {expansion_factor=4, excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {expansion_factor=4, excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {expansion_factor=4, excitation_ratio=0.25, anti_aliasing=false},
    {expansion_factor=6, excitation_ratio=0.25, anti_aliasing=false},
    {expansion_factor=6, excitation_ratio=0.25, anti_aliasing=false},
]

[decoder]
channels = [192, 154, 77, 58, 29]
upsampling_factors = [2, 2, 2, 2, 1]
stage_depths = [6, 4, 3, 3, 1]
block_factory = [
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
]
block_factory_args = [
    {expansion_factor=6, excitation_ratio=0.25, anti_aliasing=false},
    {expansion_factor=4, excitation_ratio=0.25, anti_aliasing=false},
    {expansion_factor=4, excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {expansion_factor=4, excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {expansion_factor=1, excitation_ratio=0.0, fused=true, anti_aliasing=false},
]
skip_connections=true
