[encoder]
channels = [24, 48, 64, 128, 160, 256]
downsampling_factors = [[1, 1, 1], [2, 2, 2], [1, 2, 2], [2, 2, 2], [1, 2, 2]]
stage_depths = [2, 3, 3, 4, 5, 5]
block_factory = [
    "InvertedBottleneck2Plus1",
    "InvertedBottleneck2Plus1",
    "InvertedBottleneck2Plus1",
    "InvertedBottleneck2Plus1",
    "InvertedBottleneck2Plus1",
    "InvertedBottleneck2Plus1",
]
block_factory_args = [
    {expansion_factor=1, excitation_ratio=0.0, fused=true, anti_aliasing=true},
    {expansion_factor=4, excitation_ratio=0.0, fused=true, anti_aliasing=true},
    {expansion_factor=4, excitation_ratio=0.0, fused=true, anti_aliasing=true},
    {expansion_factor=4, excitation_ratio=0.25, anti_aliasing=true},
    {expansion_factor=6, excitation_ratio=0.25, anti_aliasing=true},
    {expansion_factor=6, excitation_ratio=0.25, anti_aliasing=true},
]
aggregation_factory = "Linear3d"

[decoder]
channels = [160, 128, 64, 48, 24]
upsampling_factors = [[1, 2, 2], [2, 2, 2], [1, 2, 2], [2, 2, 2], [1, 2, 2]]
upsampling_factory = "Trilinear"
stage_depths = [5, 4, 3, 3, 2]
block_factory = [
    "InvertedBottleneck2Plus1",
    "InvertedBottleneck2Plus1",
    "InvertedBottleneck2Plus1",
    "InvertedBottleneck2Plus1",
    "InvertedBottleneck2Plus1",
]
block_factory_args = [
    {expansion_factor=6, excitation_ratio=0.25, anti_aliasing=true},
    {expansion_factor=4, excitation_ratio=0.25, anti_aliasing=true},
    {expansion_factor=4, excitation_ratio=0.0, fused=true, anti_aliasing=true},
    {expansion_factor=4, excitation_ratio=0.0, fused=true, anti_aliasing=true},
    {expansion_factor=1, excitation_ratio=0.0, fused=true, anti_aliasing=true},
]
aggregation_factory = "Linear3d"
skip_connections=true
