[stem]
depth = 1
out_channels = 16

[encoder]
channels = [16, 32, 64, 128, 256]
stage_depths = [2, 2, 2, 2, 2]
block_factory = "BasicConv"


[decoder]
channels = [128, 64, 32, 16]
stage_depths = [2, 2, 2, 2]
block_factory = "BasicConv"
